config/routes.rb
Meals::Application.routes.draw do

  root 'welcome#index'

  resources :diets do
    resources :meals
  end
  
end

app/models/diet.rb
class Diet < ActiveRecord::Base

	has_many :ingredients
	has_many :meals
	
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

	belongs_to :diet
	
end

app/models/meal.rb
class Meal < ActiveRecord::Base
	
	belongs_to :diet

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	
	def index
		@ingredients = Ingredient.all
	end

	

	
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
	def index
		@diet = Diet.find(params[:diet_id])
		@meals = @diet.meals
	end
end

app/controllers/vegan_controller.rb
class VeganController < ApplicationController
	def index
		@meals = Meal.where(diet_id: 1)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ingredients/index.html.erb
<h1>All Ingredients</h1>

<ul>
	<% @ingredients.each do |ingredient| %>
		<li>
			<%= ingredient.ingredient %>
		</li>	
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Good Plain Cook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/meals/index.html.erb
<h1>All Meals</h1>

<ul>
	<% @meals.each do |meal| %>
		<li>
			<%= meal.name %>
		</li>
	<% end %>
</ul>

app/views/welcome/index.html.erb
<h1>Good Plain Cook</h1>

<h2>what's for dinner?</h2>

<% Diet.all.each do |diet| %>
  <h3><%= link_to diet.diet, diet_meals_path(diet.id) %></h3>
<% end %>

<h2>featured vegetable</h2>

	<h3>leek</h3>
	#TODO add link_to leek when I've worked out the path

<h2>ingredients</h2>




<p>Want to sign up, or sign in? Super!</p>